services:
  - type: web
    name: investment-platform
    runtime: docker
    rootDir: backend
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: investment-db
          property: connectionString
      - key: SPRING_DATA_REDIS_URL
        fromService:
          name: investment-redis
          type: keyvalue
          property: connectionString
      - key: SERVER_PORT
        value: 10000
      - key: SECURITY_JWT_SECRET
        generateValue: true

  - type: keyvalue
    name: investment-redis
    plan: free
    ipAllowList: []

databases:
  - name: investment-db
    databaseName: investment_platform
    user: admin
    plan: free
